config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to:'tasklists#index'
resources:'tasklists'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tasklist.rb
class Tasklist < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasklist_controller.rb
class TasklistController < ApplicationController
def index
    @tasklists=tasklists.all
end

def show
    @tasklist = Tasklist.find(params[:id])
end

def new 
    @tasklist = Tasklist.new
end

def create
    @tasklist = Tasklist.new(tasklist_params)
    if @message.save
        flash[:success] = 'Tasklist が正常に投稿されました。'
        redirect_to -@tasklist
    else
        flash.now[:danger] = 'Tasklistが投稿されませんでした。'
        render :new
    end
end

def edit
end

def update
    @tasklist = Tasklist.find(params[:id])
    
    if @tasklist.update(tasklist_params)
        flash[:success] = 'Tasklist は正常に更新されました。'
        redirect_to @tasklist
    else
        flash.now[:danger] = 'Tasklistは更新されませんでした。'
        render :edit
    end
end

def destory
    @tasklist = Tasklist.find(params[:id])
    @message.destroy
    
    flash[:success] = 'Tasklist は正常に削除されました。'
    redirect_to tasklist_url
end

end

private

def message_params
    params.require(:tasklist).permit(:content)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasklist_helper.rb
module TasklistHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KadaiTasklist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/flash_tasklists' %>
       <%= yield %>
    </div>
   
  </body>
</html>

app/views/layouts/flash_tasklists.html.erb
<% flash.each do |tasklist_type,tasklist| %>
<div><%= tasklist %></div>
<% end %>

app/views/tasklist/edit.html.erb
<h1>id: <%= @tasklist.id %>のメッセージ編集ページ</h1>
<%= form_for(@tasklist) do |f| %>
<%= f.label :content, 'メッセージ' %>
<%= f.text_field:content %>

<%= f.submit '投稿' %>
<% end %>
<%= link_to'一覧に戻る',tasklist_path %>

app/views/tasklist/inidex.html.erb
<h1>メッセージ一覧</h1>
<ul>
  <% @tasklists.eace do|tasklist| %>
  <li><%= link_to tasklist.id,tasklist %>:<%= tasklist.content %></li>
  <% end %>
</ul>

<%= link_to '新規メッセージの投稿', new_message_path %>

app/views/tasklist/new.html.erb
<h1>メッセージ新規作成ページ</h1>

<%= form_for(@tasklist) do |f| %>
<%= f.label :content, 'メッセージ' %>
<%= f.text_field :content %>

<%= f.submit '投稿' %>
<% end %>
<%= link_to '一覧に戻る', tasklist_path %>

app/views/tasklist/show.html.erb
<h1>id = <%= @tasklist.id>のメッセージ詳細ページ</h1>
<p><%= @tasklist.content %></p>
<%= link_to '一覧に戻る', messages_path %>
<%= link_to'このメッセージを編集する', edit_tasklist_path(@tasklist) %>
<%= link_to 'このメッセージを削除する', @tasklist,method: delete, data{confirm:'本当に削除してよろしいですか？'} %>